name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Proper permission for pushing to repo
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake Animation (Light)
        uses: Platane/snk/svg-only@v3
        id: snake-gif-light
        with:
          github_user_name: DIX2580
          outputs: |
            dist/github-contribution-grid-snake.svg
      
      - name: Generate Snake Animation (Dark)
        uses: Platane/snk/svg-only@v3
        id: snake-gif-dark
        with:
          github_user_name: DIX2580
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
