name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  build:
    name: Snake Animation Job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: DIX2580
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'
      
      - name: Generate Snake Animation (Dark Mode)
        uses: Platane/snk@master
        if: always()
        id: snake-gif-dark
        with:
          github_user_name: DIX2580
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
